{% set name = "mira-simpeg" %}
{% set version = "0.21.2.1" %}
{% set python_min = "3.10" %}
{% set python_max = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MiraGeoscience/simpeg/archive/v{{ version }}+mira.tar.gz
  sha256: 430eec3e3a8dadd4787f63f2917bc9a0d853fb87562900b32955f71e9268b22d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - setuptools
    - pip
  run:
    - python >={{ python_min }},<{{ python_max }}
    - discretize >=0.8.0
    - empymod >=2.0.0
    - geoana
    - geoh5py
    - matplotlib-base
    - numpy >=1.20
    - pandas
    - pymatsolver >=0.2
    - scikit-learn >=1.2
    - scipy >=1.8.0
  run_constrained:
    - dask-core *
    - distributed *
    - fsspec >=0.3.3
    - zarr *

test:
  imports:
    - SimPEG
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://docs.simpeg.xyz/
  summary: 'Mira Geoscience fork of SimPEG: Simulation and Parameter Estimation in Geophysics'
  description: |
    Simulation and Parameter Estimation in Geophysics - A python package for simulation and 
    gradient based parameter estimation in the context of geophysical applications.
  
    Warning:
    This is a fork created by Mira Geoscience.
  license: MIT
  license_file: 
    - LICENSE
  doc_url: https://docs.simpeg.xyz/
  dev_url: https://github.com/MiraGeoscience/simpeg

extra:
  recipe-maintainers:
    - conda-forge/geoh5py
