{% set name = "mira_simpeg" %}
{% set version = "0.21.2.1" %}
{% set python_min = "3.10" %}
{% set python_max = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 460f86cbfdc1defe86da085ba3b8dd84516e8346c58bd3f1b48edc4290b0276e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=64
    - setuptools_scm >=8
  run:
    - python >={{ python_min }},<{{ python_max }}
    - discretize >=0.10.0
    - empymod >=2.0.0
    - geoana >=0.5.0
    - geoh5py >=0.1.0,<0.11.dev
    - libdlf
    - matplotlib-base
    - numpy >=1.20
    - pandas
    - pymatsolver >=0.2,<0.3
    - scikit-learn >=1.2
    - scipy >=1.8
  run_constrained:
    - choclo >=0.1.0
    - fsspec >=0.3.3

test:
  imports:
    - simpeg
    - simpeg.electromagnetics
    - simpeg.electromagnetics.analytics
    - simpeg.electromagnetics.frequency_domain
    - simpeg.electromagnetics.natural_source
    - simpeg.electromagnetics.natural_source.utils
    - simpeg.electromagnetics.static
    - simpeg.electromagnetics.static.resistivity
    - simpeg.electromagnetics.static.induced_polarization
    - simpeg.electromagnetics.static.spectral_induced_polarization
    - simpeg.electromagnetics.static.utils
    - simpeg.electromagnetics.time_domain
    - simpeg.electromagnetics.utils
    - simpeg.electromagnetics.viscous_remanent_magnetization
    - simpeg.flow
    - simpeg.flow.richards
    - simpeg.potential_fields
    - simpeg.potential_fields.gravity
    - simpeg.potential_fields.magnetics
    - simpeg.seismic
    - simpeg.seismic.straight_ray_tomography
    - simpeg.utils
    - simpeg.utils.drivers
    - simpeg.regularization
    - simpeg.meta
    - geoh5py
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://docs.simpeg.xyz/
  summary: 'Mira Geoscience fork of SimPEG: Simulation and Parameter Estimation in Geophysics'
  description: |
    Simulation and Parameter Estimation in Geophysics - A python package for simulation and 
    gradient based parameter estimation in the context of geophysical applications.
  
    Warning:
    This is a fork created by Mira Geoscience.
  license: MIT
  license_file: 
    - LICENSE
  doc_url: https://docs.simpeg.xyz/
  dev_url: https://github.com/MiraGeoscience/simpeg

extra:
  recipe-maintainers:
    - conda-forge/geoh5py
